root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["--http-port", "8088", "--dangerously-skip-permissions"]
  bin = "./build/debug/mix"
  cmd = "go build -o ./build/debug/mix ./main.go "
  delay = 0
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "build"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_ext = ["go", "tpl", "tmpl", "html", "md"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_root = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = true
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true