package models

const (
	ProviderAnthropic     ModelProvider = "anthropic"
	ProviderAzureFoundry  ModelProvider = "azure-foundry"

	// Models
	Claude35Sonnet ModelID = "claude-3.5-sonnet"
	Claude3Haiku   ModelID = "claude-3-haiku"
	Claude37Sonnet ModelID = "claude-3.7-sonnet"
	Claude35Haiku  ModelID = "claude-3.5-haiku"
	Claude3Opus    ModelID = "claude-3-opus"
	Claude4Opus    ModelID = "claude-4-opus"
	Claude4Sonnet  ModelID = "claude-4-sonnet"
	Claude45Sonnet ModelID = "claude-sonnet-4-5"
)

// https://docs.anthropic.com/en/docs/about-claude/models/all-models
var AnthropicModels = map[ModelID]Model{
	Claude37Sonnet: {
		ID:                  Claude37Sonnet,
		Name:                "Claude 3.7 Sonnet",
		Provider:            ProviderAnthropic,
		APIModel:            "claude-3-7-sonnet-latest",
		CostPer1MIn:         3.0,
		CostPer1MInCached:   3.75,
		CostPer1MOutCached:  0.30,
		CostPer1MOut:        15.0,
		ContextWindow:       200000,
		DefaultMaxTokens:    50000,
		CanReason:           true,
		SupportsAttachments: true,
	},
	Claude35Haiku: {
		ID:                  Claude35Haiku,
		Name:                "Claude 3.5 Haiku",
		Provider:            ProviderAnthropic,
		APIModel:            "claude-3-5-haiku-latest",
		CostPer1MIn:         0.80,
		CostPer1MInCached:   1.0,
		CostPer1MOutCached:  0.08,
		CostPer1MOut:        4.0,
		ContextWindow:       200000,
		DefaultMaxTokens:    4096,
		SupportsAttachments: true,
	},
	Claude3Opus: {
		ID:                  Claude3Opus,
		Name:                "Claude 3 Opus",
		Provider:            ProviderAnthropic,
		APIModel:            "claude-3-opus-latest",
		CostPer1MIn:         15.0,
		CostPer1MInCached:   18.75,
		CostPer1MOutCached:  1.50,
		CostPer1MOut:        75.0,
		ContextWindow:       200000,
		DefaultMaxTokens:    4096,
		SupportsAttachments: true,
	},
	Claude45Sonnet: {
		ID:                  Claude45Sonnet,
		Name:                "Claude 4 5 Sonnet",
		Provider:            ProviderAnthropic,
		APIModel:            "claude-sonnet-4-5-20250929",
		CostPer1MIn:         3.0,
		CostPer1MInCached:   3.75,
		CostPer1MOutCached:  0.30,
		CostPer1MOut:        15.0,
		ContextWindow:       200000,
		DefaultMaxTokens:    50000,
		CanReason:           true,
		SupportsAttachments: true,
	},
	Claude4Sonnet: {
		ID:                  Claude4Sonnet,
		Name:                "Claude 4 Sonnet",
		Provider:            ProviderAnthropic,
		APIModel:            "claude-sonnet-4-20250514",
		CostPer1MIn:         3.0,
		CostPer1MInCached:   3.75,
		CostPer1MOutCached:  0.30,
		CostPer1MOut:        15.0,
		ContextWindow:       200000,
		DefaultMaxTokens:    50000,
		CanReason:           true,
		SupportsAttachments: true,
	},
	Claude4Opus: {
		ID:                  Claude4Opus,
		Name:                "Claude 4 Opus",
		Provider:            ProviderAnthropic,
		APIModel:            "claude-opus-4-20250514",
		CostPer1MIn:         15.0,
		CostPer1MInCached:   18.75,
		CostPer1MOutCached:  1.50,
		CostPer1MOut:        75.0,
		ContextWindow:       200000,
		DefaultMaxTokens:    4096,
		SupportsAttachments: true,
	},
}

// AzureFoundryModels reuses Anthropic models with Azure Foundry provider
// Azure Foundry uses simpler model names without version dates
var AzureFoundryModels = map[ModelID]Model{
	Claude45Sonnet: {
		ID:                  Claude45Sonnet,
		Name:                "Azure Foundry – Claude 4.5 Sonnet",
		Provider:            ProviderAzureFoundry,
		APIModel:            "claude-sonnet-4-5",
		CostPer1MIn:         AnthropicModels[Claude45Sonnet].CostPer1MIn,
		CostPer1MInCached:   AnthropicModels[Claude45Sonnet].CostPer1MInCached,
		CostPer1MOut:        AnthropicModels[Claude45Sonnet].CostPer1MOut,
		CostPer1MOutCached:  AnthropicModels[Claude45Sonnet].CostPer1MOutCached,
		ContextWindow:       AnthropicModels[Claude45Sonnet].ContextWindow,
		DefaultMaxTokens:    AnthropicModels[Claude45Sonnet].DefaultMaxTokens,
		CanReason:           AnthropicModels[Claude45Sonnet].CanReason,
		SupportsAttachments: AnthropicModels[Claude45Sonnet].SupportsAttachments,
	},
	Claude4Sonnet: {
		ID:                  Claude4Sonnet,
		Name:                "Azure Foundry – Claude 4 Sonnet",
		Provider:            ProviderAzureFoundry,
		APIModel:            "claude-sonnet-4",
		CostPer1MIn:         AnthropicModels[Claude4Sonnet].CostPer1MIn,
		CostPer1MInCached:   AnthropicModels[Claude4Sonnet].CostPer1MInCached,
		CostPer1MOut:        AnthropicModels[Claude4Sonnet].CostPer1MOut,
		CostPer1MOutCached:  AnthropicModels[Claude4Sonnet].CostPer1MOutCached,
		ContextWindow:       AnthropicModels[Claude4Sonnet].ContextWindow,
		DefaultMaxTokens:    AnthropicModels[Claude4Sonnet].DefaultMaxTokens,
		CanReason:           AnthropicModels[Claude4Sonnet].CanReason,
		SupportsAttachments: AnthropicModels[Claude4Sonnet].SupportsAttachments,
	},
	Claude37Sonnet: {
		ID:                  Claude37Sonnet,
		Name:                "Azure Foundry – Claude 3.7 Sonnet",
		Provider:            ProviderAzureFoundry,
		APIModel:            "claude-3-7-sonnet",
		CostPer1MIn:         AnthropicModels[Claude37Sonnet].CostPer1MIn,
		CostPer1MInCached:   AnthropicModels[Claude37Sonnet].CostPer1MInCached,
		CostPer1MOut:        AnthropicModels[Claude37Sonnet].CostPer1MOut,
		CostPer1MOutCached:  AnthropicModels[Claude37Sonnet].CostPer1MOutCached,
		ContextWindow:       AnthropicModels[Claude37Sonnet].ContextWindow,
		DefaultMaxTokens:    AnthropicModels[Claude37Sonnet].DefaultMaxTokens,
		CanReason:           AnthropicModels[Claude37Sonnet].CanReason,
		SupportsAttachments: AnthropicModels[Claude37Sonnet].SupportsAttachments,
	},
	Claude4Opus: {
		ID:                  Claude4Opus,
		Name:                "Azure Foundry – Claude 4 Opus",
		Provider:            ProviderAzureFoundry,
		APIModel:            "claude-opus-4",
		CostPer1MIn:         AnthropicModels[Claude4Opus].CostPer1MIn,
		CostPer1MInCached:   AnthropicModels[Claude4Opus].CostPer1MInCached,
		CostPer1MOut:        AnthropicModels[Claude4Opus].CostPer1MOut,
		CostPer1MOutCached:  AnthropicModels[Claude4Opus].CostPer1MOutCached,
		ContextWindow:       AnthropicModels[Claude4Opus].ContextWindow,
		DefaultMaxTokens:    AnthropicModels[Claude4Opus].DefaultMaxTokens,
		CanReason:           AnthropicModels[Claude4Opus].CanReason,
		SupportsAttachments: AnthropicModels[Claude4Opus].SupportsAttachments,
	},
	Claude35Haiku: {
		ID:                  Claude35Haiku,
		Name:                "Azure Foundry – Claude 3.5 Haiku",
		Provider:            ProviderAzureFoundry,
		APIModel:            "claude-3-5-haiku",
		CostPer1MIn:         AnthropicModels[Claude35Haiku].CostPer1MIn,
		CostPer1MInCached:   AnthropicModels[Claude35Haiku].CostPer1MInCached,
		CostPer1MOut:        AnthropicModels[Claude35Haiku].CostPer1MOut,
		CostPer1MOutCached:  AnthropicModels[Claude35Haiku].CostPer1MOutCached,
		ContextWindow:       AnthropicModels[Claude35Haiku].ContextWindow,
		DefaultMaxTokens:    AnthropicModels[Claude35Haiku].DefaultMaxTokens,
		CanReason:           AnthropicModels[Claude35Haiku].CanReason,
		SupportsAttachments: AnthropicModels[Claude35Haiku].SupportsAttachments,
	},
	Claude3Opus: {
		ID:                  Claude3Opus,
		Name:                "Azure Foundry – Claude 3 Opus",
		Provider:            ProviderAzureFoundry,
		APIModel:            "claude-3-opus",
		CostPer1MIn:         AnthropicModels[Claude3Opus].CostPer1MIn,
		CostPer1MInCached:   AnthropicModels[Claude3Opus].CostPer1MInCached,
		CostPer1MOut:        AnthropicModels[Claude3Opus].CostPer1MOut,
		CostPer1MOutCached:  AnthropicModels[Claude3Opus].CostPer1MOutCached,
		ContextWindow:       AnthropicModels[Claude3Opus].ContextWindow,
		DefaultMaxTokens:    AnthropicModels[Claude3Opus].DefaultMaxTokens,
		CanReason:           AnthropicModels[Claude3Opus].CanReason,
		SupportsAttachments: AnthropicModels[Claude3Opus].SupportsAttachments,
	},
}
