// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: api_credentials.sql

package db

import (
	"context"
)

const createAPICredential = `-- name: CreateAPICredential :one
INSERT INTO api_credentials (
    id, provider, api_key, created_at, updated_at
) VALUES (
    'default_user', ?, ?, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000
) RETURNING id, provider, api_key, created_at, updated_at`

type CreateAPICredentialParams struct {
	Provider string `json:"provider"`
	ApiKey   string `json:"api_key"`
}

func (q *Queries) CreateAPICredential(ctx context.Context, arg CreateAPICredentialParams) (ApiCredential, error) {
	row := q.db.QueryRowContext(ctx, createAPICredential, arg.Provider, arg.ApiKey)
	var i ApiCredential
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAPICredential = `-- name: DeleteAPICredential :exec
DELETE FROM api_credentials 
WHERE id = 'default_user' AND provider = ?`

func (q *Queries) DeleteAPICredential(ctx context.Context, provider string) error {
	_, err := q.db.ExecContext(ctx, deleteAPICredential, provider)
	return err
}

const deleteAllAPICredentials = `-- name: DeleteAllAPICredentials :exec
DELETE FROM api_credentials 
WHERE id = 'default_user'`

func (q *Queries) DeleteAllAPICredentials(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllAPICredentials)
	return err
}

const getAPICredential = `-- name: GetAPICredential :one
SELECT id, provider, api_key, created_at, updated_at
FROM api_credentials 
WHERE id = 'default_user' AND provider = ?`

func (q *Queries) GetAPICredential(ctx context.Context, provider string) (ApiCredential, error) {
	row := q.db.QueryRowContext(ctx, getAPICredential, provider)
	var i ApiCredential
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasAPICredential = `-- name: HasAPICredential :one
SELECT COUNT(*) as count
FROM api_credentials 
WHERE id = 'default_user' AND provider = ? AND api_key IS NOT NULL AND api_key != ''`

func (q *Queries) HasAPICredential(ctx context.Context, provider string) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasAPICredential, provider)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAPICredentials = `-- name: ListAPICredentials :many
SELECT id, provider, api_key, created_at, updated_at
FROM api_credentials 
WHERE id = 'default_user'
ORDER BY provider`

func (q *Queries) ListAPICredentials(ctx context.Context) ([]ApiCredential, error) {
	rows, err := q.db.QueryContext(ctx, listAPICredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiCredential
	for rows.Next() {
		var i ApiCredential
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ApiKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPICredential = `-- name: UpdateAPICredential :one
UPDATE api_credentials 
SET api_key = ?, updated_at = strftime('%s', 'now') * 1000
WHERE id = 'default_user' AND provider = ?
RETURNING id, provider, api_key, created_at, updated_at`

type UpdateAPICredentialParams struct {
	ApiKey   string `json:"api_key"`
	Provider string `json:"provider"`
}

func (q *Queries) UpdateAPICredential(ctx context.Context, arg UpdateAPICredentialParams) (ApiCredential, error) {
	row := q.db.QueryRowContext(ctx, updateAPICredential, arg.ApiKey, arg.Provider)
	var i ApiCredential
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAPICredential = `-- name: UpsertAPICredential :one
INSERT INTO api_credentials (
    id, provider, api_key, created_at, updated_at
) VALUES (
    'default_user', ?, ?, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000
) ON CONFLICT(id, provider) DO UPDATE SET
    api_key = excluded.api_key,
    updated_at = strftime('%s', 'now') * 1000
RETURNING id, provider, api_key, created_at, updated_at`

type UpsertAPICredentialParams struct {
	Provider string `json:"provider"`
	ApiKey   string `json:"api_key"`
}

func (q *Queries) UpsertAPICredential(ctx context.Context, arg UpsertAPICredentialParams) (ApiCredential, error) {
	row := q.db.QueryRowContext(ctx, upsertAPICredential, arg.Provider, arg.ApiKey)
	var i ApiCredential
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}