// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type ApiCredential struct {
	UserID    int64  `json:"user_id"`
	ID        string `json:"id"`
	Provider  string `json:"provider"`
	ApiKey    string `json:"api_key"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type File struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	Content   string `json:"content"`
	Version   string `json:"version"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type Message struct {
	ID         string         `json:"id"`
	SessionID  string         `json:"session_id"`
	Role       string         `json:"role"`
	Parts      string         `json:"parts"`
	Model      sql.NullString `json:"model"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
	FinishedAt sql.NullInt64  `json:"finished_at"`
}

type Session struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Title            string         `json:"title"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
	UpdatedAt        int64          `json:"updated_at"`
	CreatedAt        int64          `json:"created_at"`
	SummaryMessageID sql.NullString `json:"summary_message_id"`
	WorkingDirectory sql.NullString `json:"working_directory"`
}

type UserPreference struct {
	ID                      string         `json:"id"`
	PreferredProvider       sql.NullString `json:"preferred_provider"`
	MainAgentModel          sql.NullString `json:"main_agent_model"`
	MainAgentMaxTokens      sql.NullInt64  `json:"main_agent_max_tokens"`
	MainAgentReasoningEffort sql.NullString `json:"main_agent_reasoning_effort"`
	SubAgentModel           sql.NullString `json:"sub_agent_model"`
	SubAgentMaxTokens       sql.NullInt64  `json:"sub_agent_max_tokens"`
	SubAgentReasoningEffort sql.NullString `json:"sub_agent_reasoning_effort"`
	CreatedAt               int64          `json:"created_at"`
	UpdatedAt               int64          `json:"updated_at"`
}