// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createAPICredentialStmt, err = db.PrepareContext(ctx, createAPICredential); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAPICredential: %w", err)
	}
	if q.createFileStmt, err = db.PrepareContext(ctx, createFile); err != nil {
		return nil, fmt.Errorf("error preparing query CreateFile: %w", err)
	}
	if q.createMessageStmt, err = db.PrepareContext(ctx, createMessage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMessage: %w", err)
	}
	if q.createOAuthCredentialStmt, err = db.PrepareContext(ctx, createOAuthCredential); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOAuthCredential: %w", err)
	}
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.createUserPreferencesStmt, err = db.PrepareContext(ctx, createUserPreferences); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUserPreferences: %w", err)
	}
	if q.deleteAPICredentialStmt, err = db.PrepareContext(ctx, deleteAPICredential); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAPICredential: %w", err)
	}
	if q.deleteAllAPICredentialsStmt, err = db.PrepareContext(ctx, deleteAllAPICredentials); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllAPICredentials: %w", err)
	}
	if q.deleteAllOAuthCredentialsStmt, err = db.PrepareContext(ctx, deleteAllOAuthCredentials); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllOAuthCredentials: %w", err)
	}
	if q.deleteFileStmt, err = db.PrepareContext(ctx, deleteFile); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFile: %w", err)
	}
	if q.deleteMessageStmt, err = db.PrepareContext(ctx, deleteMessage); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMessage: %w", err)
	}
	if q.deleteOAuthCredentialStmt, err = db.PrepareContext(ctx, deleteOAuthCredential); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteOAuthCredential: %w", err)
	}
	if q.deleteSessionStmt, err = db.PrepareContext(ctx, deleteSession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSession: %w", err)
	}
	if q.getAPICredentialStmt, err = db.PrepareContext(ctx, getAPICredential); err != nil {
		return nil, fmt.Errorf("error preparing query GetAPICredential: %w", err)
	}
	if q.getFileStmt, err = db.PrepareContext(ctx, getFile); err != nil {
		return nil, fmt.Errorf("error preparing query GetFile: %w", err)
	}
	if q.getFileByPathAndSessionStmt, err = db.PrepareContext(ctx, getFileByPathAndSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileByPathAndSession: %w", err)
	}
	if q.getMessageStmt, err = db.PrepareContext(ctx, getMessage); err != nil {
		return nil, fmt.Errorf("error preparing query GetMessage: %w", err)
	}
	if q.getOAuthCredentialStmt, err = db.PrepareContext(ctx, getOAuthCredential); err != nil {
		return nil, fmt.Errorf("error preparing query GetOAuthCredential: %w", err)
	}
	if q.getSessionByIDStmt, err = db.PrepareContext(ctx, getSessionByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionByID: %w", err)
	}
	if q.getUserPreferencesStmt, err = db.PrepareContext(ctx, getUserPreferences); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserPreferences: %w", err)
	}
	if q.hasAPICredentialStmt, err = db.PrepareContext(ctx, hasAPICredential); err != nil {
		return nil, fmt.Errorf("error preparing query HasAPICredential: %w", err)
	}
	if q.hasOAuthCredentialStmt, err = db.PrepareContext(ctx, hasOAuthCredential); err != nil {
		return nil, fmt.Errorf("error preparing query HasOAuthCredential: %w", err)
	}
	if q.listAPICredentialsStmt, err = db.PrepareContext(ctx, listAPICredentials); err != nil {
		return nil, fmt.Errorf("error preparing query ListAPICredentials: %w", err)
	}
	if q.listExpiredOAuthCredentialsStmt, err = db.PrepareContext(ctx, listExpiredOAuthCredentials); err != nil {
		return nil, fmt.Errorf("error preparing query ListExpiredOAuthCredentials: %w", err)
	}
	if q.listFilesByPathStmt, err = db.PrepareContext(ctx, listFilesByPath); err != nil {
		return nil, fmt.Errorf("error preparing query ListFilesByPath: %w", err)
	}
	if q.listFilesBySessionStmt, err = db.PrepareContext(ctx, listFilesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListFilesBySession: %w", err)
	}
	if q.listLatestSessionFilesStmt, err = db.PrepareContext(ctx, listLatestSessionFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListLatestSessionFiles: %w", err)
	}
	if q.listMessagesBySessionStmt, err = db.PrepareContext(ctx, listMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessagesBySession: %w", err)
	}
	if q.listMessagesForForkStmt, err = db.PrepareContext(ctx, listMessagesForFork); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessagesForFork: %w", err)
	}
	if q.listOAuthCredentialsStmt, err = db.PrepareContext(ctx, listOAuthCredentials); err != nil {
		return nil, fmt.Errorf("error preparing query ListOAuthCredentials: %w", err)
	}
	if q.listSessionsMetadataStmt, err = db.PrepareContext(ctx, listSessionsMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionsMetadata: %w", err)
	}
	if q.listSessionsWithContentStmt, err = db.PrepareContext(ctx, listSessionsWithContent); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionsWithContent: %w", err)
	}
	if q.listUserMessageHistoryStmt, err = db.PrepareContext(ctx, listUserMessageHistory); err != nil {
		return nil, fmt.Errorf("error preparing query ListUserMessageHistory: %w", err)
	}
	if q.resetUserPreferencesToDefaultsStmt, err = db.PrepareContext(ctx, resetUserPreferencesToDefaults); err != nil {
		return nil, fmt.Errorf("error preparing query ResetUserPreferencesToDefaults: %w", err)
	}
	if q.updateAPICredentialStmt, err = db.PrepareContext(ctx, updateAPICredential); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAPICredential: %w", err)
	}
	if q.updateFileStmt, err = db.PrepareContext(ctx, updateFile); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateFile: %w", err)
	}
	if q.updateMainAgentModelStmt, err = db.PrepareContext(ctx, updateMainAgentModel); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMainAgentModel: %w", err)
	}
	if q.updateMessageStmt, err = db.PrepareContext(ctx, updateMessage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMessage: %w", err)
	}
	if q.updateOAuthCredentialStmt, err = db.PrepareContext(ctx, updateOAuthCredential); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateOAuthCredential: %w", err)
	}
	if q.updateSessionStmt, err = db.PrepareContext(ctx, updateSession); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSession: %w", err)
	}
	if q.updateSubAgentModelStmt, err = db.PrepareContext(ctx, updateSubAgentModel); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSubAgentModel: %w", err)
	}
	if q.updateUserPreferencesStmt, err = db.PrepareContext(ctx, updateUserPreferences); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserPreferences: %w", err)
	}
	if q.updateUserPreferredProviderStmt, err = db.PrepareContext(ctx, updateUserPreferredProvider); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserPreferredProvider: %w", err)
	}
	if q.upsertAPICredentialStmt, err = db.PrepareContext(ctx, upsertAPICredential); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertAPICredential: %w", err)
	}
	if q.upsertOAuthCredentialStmt, err = db.PrepareContext(ctx, upsertOAuthCredential); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertOAuthCredential: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createAPICredentialStmt != nil {
		if cerr := q.createAPICredentialStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAPICredentialStmt: %w", cerr)
		}
	}
	if q.createFileStmt != nil {
		if cerr := q.createFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createFileStmt: %w", cerr)
		}
	}
	if q.createMessageStmt != nil {
		if cerr := q.createMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMessageStmt: %w", cerr)
		}
	}
	if q.createOAuthCredentialStmt != nil {
		if cerr := q.createOAuthCredentialStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOAuthCredentialStmt: %w", cerr)
		}
	}
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.createUserPreferencesStmt != nil {
		if cerr := q.createUserPreferencesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserPreferencesStmt: %w", cerr)
		}
	}
	if q.deleteAPICredentialStmt != nil {
		if cerr := q.deleteAPICredentialStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAPICredentialStmt: %w", cerr)
		}
	}
	if q.deleteAllAPICredentialsStmt != nil {
		if cerr := q.deleteAllAPICredentialsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllAPICredentialsStmt: %w", cerr)
		}
	}
	if q.deleteAllOAuthCredentialsStmt != nil {
		if cerr := q.deleteAllOAuthCredentialsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllOAuthCredentialsStmt: %w", cerr)
		}
	}
	if q.deleteFileStmt != nil {
		if cerr := q.deleteFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFileStmt: %w", cerr)
		}
	}
	if q.deleteMessageStmt != nil {
		if cerr := q.deleteMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMessageStmt: %w", cerr)
		}
	}
	if q.deleteOAuthCredentialStmt != nil {
		if cerr := q.deleteOAuthCredentialStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteOAuthCredentialStmt: %w", cerr)
		}
	}
	if q.deleteSessionStmt != nil {
		if cerr := q.deleteSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionStmt: %w", cerr)
		}
	}
	if q.getAPICredentialStmt != nil {
		if cerr := q.getAPICredentialStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAPICredentialStmt: %w", cerr)
		}
	}
	if q.getFileStmt != nil {
		if cerr := q.getFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileStmt: %w", cerr)
		}
	}
	if q.getFileByPathAndSessionStmt != nil {
		if cerr := q.getFileByPathAndSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileByPathAndSessionStmt: %w", cerr)
		}
	}
	if q.getMessageStmt != nil {
		if cerr := q.getMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMessageStmt: %w", cerr)
		}
	}
	if q.getOAuthCredentialStmt != nil {
		if cerr := q.getOAuthCredentialStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOAuthCredentialStmt: %w", cerr)
		}
	}
	if q.getSessionByIDStmt != nil {
		if cerr := q.getSessionByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionByIDStmt: %w", cerr)
		}
	}
	if q.getUserPreferencesStmt != nil {
		if cerr := q.getUserPreferencesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserPreferencesStmt: %w", cerr)
		}
	}
	if q.hasAPICredentialStmt != nil {
		if cerr := q.hasAPICredentialStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing hasAPICredentialStmt: %w", cerr)
		}
	}
	if q.hasOAuthCredentialStmt != nil {
		if cerr := q.hasOAuthCredentialStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing hasOAuthCredentialStmt: %w", cerr)
		}
	}
	if q.listAPICredentialsStmt != nil {
		if cerr := q.listAPICredentialsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAPICredentialsStmt: %w", cerr)
		}
	}
	if q.listExpiredOAuthCredentialsStmt != nil {
		if cerr := q.listExpiredOAuthCredentialsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listExpiredOAuthCredentialsStmt: %w", cerr)
		}
	}
	if q.listFilesByPathStmt != nil {
		if cerr := q.listFilesByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFilesByPathStmt: %w", cerr)
		}
	}
	if q.listFilesBySessionStmt != nil {
		if cerr := q.listFilesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFilesBySessionStmt: %w", cerr)
		}
	}
	if q.listLatestSessionFilesStmt != nil {
		if cerr := q.listLatestSessionFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLatestSessionFilesStmt: %w", cerr)
		}
	}
	if q.listMessagesBySessionStmt != nil {
		if cerr := q.listMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.listMessagesForForkStmt != nil {
		if cerr := q.listMessagesForForkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesForForkStmt: %w", cerr)
		}
	}
	if q.listOAuthCredentialsStmt != nil {
		if cerr := q.listOAuthCredentialsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listOAuthCredentialsStmt: %w", cerr)
		}
	}
	if q.listSessionsMetadataStmt != nil {
		if cerr := q.listSessionsMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsMetadataStmt: %w", cerr)
		}
	}
	if q.listSessionsWithContentStmt != nil {
		if cerr := q.listSessionsWithContentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsWithContentStmt: %w", cerr)
		}
	}
	if q.listUserMessageHistoryStmt != nil {
		if cerr := q.listUserMessageHistoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUserMessageHistoryStmt: %w", cerr)
		}
	}
	if q.resetUserPreferencesToDefaultsStmt != nil {
		if cerr := q.resetUserPreferencesToDefaultsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing resetUserPreferencesToDefaultsStmt: %w", cerr)
		}
	}
	if q.updateAPICredentialStmt != nil {
		if cerr := q.updateAPICredentialStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAPICredentialStmt: %w", cerr)
		}
	}
	if q.updateFileStmt != nil {
		if cerr := q.updateFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateFileStmt: %w", cerr)
		}
	}
	if q.updateMainAgentModelStmt != nil {
		if cerr := q.updateMainAgentModelStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMainAgentModelStmt: %w", cerr)
		}
	}
	if q.updateMessageStmt != nil {
		if cerr := q.updateMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMessageStmt: %w", cerr)
		}
	}
	if q.updateOAuthCredentialStmt != nil {
		if cerr := q.updateOAuthCredentialStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateOAuthCredentialStmt: %w", cerr)
		}
	}
	if q.updateSessionStmt != nil {
		if cerr := q.updateSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionStmt: %w", cerr)
		}
	}
	if q.updateSubAgentModelStmt != nil {
		if cerr := q.updateSubAgentModelStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSubAgentModelStmt: %w", cerr)
		}
	}
	if q.updateUserPreferencesStmt != nil {
		if cerr := q.updateUserPreferencesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserPreferencesStmt: %w", cerr)
		}
	}
	if q.updateUserPreferredProviderStmt != nil {
		if cerr := q.updateUserPreferredProviderStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserPreferredProviderStmt: %w", cerr)
		}
	}
	if q.upsertAPICredentialStmt != nil {
		if cerr := q.upsertAPICredentialStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertAPICredentialStmt: %w", cerr)
		}
	}
	if q.upsertOAuthCredentialStmt != nil {
		if cerr := q.upsertOAuthCredentialStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertOAuthCredentialStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                 DBTX
	tx                                 *sql.Tx
	createAPICredentialStmt            *sql.Stmt
	createFileStmt                     *sql.Stmt
	createMessageStmt                  *sql.Stmt
	createOAuthCredentialStmt          *sql.Stmt
	createSessionStmt                  *sql.Stmt
	createUserPreferencesStmt          *sql.Stmt
	deleteAPICredentialStmt            *sql.Stmt
	deleteAllAPICredentialsStmt        *sql.Stmt
	deleteAllOAuthCredentialsStmt      *sql.Stmt
	deleteFileStmt                     *sql.Stmt
	deleteMessageStmt                  *sql.Stmt
	deleteOAuthCredentialStmt          *sql.Stmt
	deleteSessionStmt                  *sql.Stmt
	getAPICredentialStmt               *sql.Stmt
	getFileStmt                        *sql.Stmt
	getFileByPathAndSessionStmt        *sql.Stmt
	getMessageStmt                     *sql.Stmt
	getOAuthCredentialStmt             *sql.Stmt
	getSessionByIDStmt                 *sql.Stmt
	getUserPreferencesStmt             *sql.Stmt
	hasAPICredentialStmt               *sql.Stmt
	hasOAuthCredentialStmt             *sql.Stmt
	listAPICredentialsStmt             *sql.Stmt
	listExpiredOAuthCredentialsStmt    *sql.Stmt
	listFilesByPathStmt                *sql.Stmt
	listFilesBySessionStmt             *sql.Stmt
	listLatestSessionFilesStmt         *sql.Stmt
	listMessagesBySessionStmt          *sql.Stmt
	listMessagesForForkStmt            *sql.Stmt
	listOAuthCredentialsStmt           *sql.Stmt
	listSessionsMetadataStmt           *sql.Stmt
	listSessionsWithContentStmt        *sql.Stmt
	listUserMessageHistoryStmt         *sql.Stmt
	resetUserPreferencesToDefaultsStmt *sql.Stmt
	updateAPICredentialStmt            *sql.Stmt
	updateFileStmt                     *sql.Stmt
	updateMainAgentModelStmt           *sql.Stmt
	updateMessageStmt                  *sql.Stmt
	updateOAuthCredentialStmt          *sql.Stmt
	updateSessionStmt                  *sql.Stmt
	updateSubAgentModelStmt            *sql.Stmt
	updateUserPreferencesStmt          *sql.Stmt
	updateUserPreferredProviderStmt    *sql.Stmt
	upsertAPICredentialStmt            *sql.Stmt
	upsertOAuthCredentialStmt          *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                 tx,
		tx:                                 tx,
		createAPICredentialStmt:            q.createAPICredentialStmt,
		createFileStmt:                     q.createFileStmt,
		createMessageStmt:                  q.createMessageStmt,
		createOAuthCredentialStmt:          q.createOAuthCredentialStmt,
		createSessionStmt:                  q.createSessionStmt,
		createUserPreferencesStmt:          q.createUserPreferencesStmt,
		deleteAPICredentialStmt:            q.deleteAPICredentialStmt,
		deleteAllAPICredentialsStmt:        q.deleteAllAPICredentialsStmt,
		deleteAllOAuthCredentialsStmt:      q.deleteAllOAuthCredentialsStmt,
		deleteFileStmt:                     q.deleteFileStmt,
		deleteMessageStmt:                  q.deleteMessageStmt,
		deleteOAuthCredentialStmt:          q.deleteOAuthCredentialStmt,
		deleteSessionStmt:                  q.deleteSessionStmt,
		getAPICredentialStmt:               q.getAPICredentialStmt,
		getFileStmt:                        q.getFileStmt,
		getFileByPathAndSessionStmt:        q.getFileByPathAndSessionStmt,
		getMessageStmt:                     q.getMessageStmt,
		getOAuthCredentialStmt:             q.getOAuthCredentialStmt,
		getSessionByIDStmt:                 q.getSessionByIDStmt,
		getUserPreferencesStmt:             q.getUserPreferencesStmt,
		hasAPICredentialStmt:               q.hasAPICredentialStmt,
		hasOAuthCredentialStmt:             q.hasOAuthCredentialStmt,
		listAPICredentialsStmt:             q.listAPICredentialsStmt,
		listExpiredOAuthCredentialsStmt:    q.listExpiredOAuthCredentialsStmt,
		listFilesByPathStmt:                q.listFilesByPathStmt,
		listFilesBySessionStmt:             q.listFilesBySessionStmt,
		listLatestSessionFilesStmt:         q.listLatestSessionFilesStmt,
		listMessagesBySessionStmt:          q.listMessagesBySessionStmt,
		listMessagesForForkStmt:            q.listMessagesForForkStmt,
		listOAuthCredentialsStmt:           q.listOAuthCredentialsStmt,
		listSessionsMetadataStmt:           q.listSessionsMetadataStmt,
		listSessionsWithContentStmt:        q.listSessionsWithContentStmt,
		listUserMessageHistoryStmt:         q.listUserMessageHistoryStmt,
		resetUserPreferencesToDefaultsStmt: q.resetUserPreferencesToDefaultsStmt,
		updateAPICredentialStmt:            q.updateAPICredentialStmt,
		updateFileStmt:                     q.updateFileStmt,
		updateMainAgentModelStmt:           q.updateMainAgentModelStmt,
		updateMessageStmt:                  q.updateMessageStmt,
		updateOAuthCredentialStmt:          q.updateOAuthCredentialStmt,
		updateSessionStmt:                  q.updateSessionStmt,
		updateSubAgentModelStmt:            q.updateSubAgentModelStmt,
		updateUserPreferencesStmt:          q.updateUserPreferencesStmt,
		updateUserPreferredProviderStmt:    q.updateUserPreferredProviderStmt,
		upsertAPICredentialStmt:            q.upsertAPICredentialStmt,
		upsertOAuthCredentialStmt:          q.upsertOAuthCredentialStmt,
	}
}
