// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_credentials.sql

package db

import (
	"context"
	"database/sql"
)

const createOAuthCredential = `-- name: CreateOAuthCredential :one
INSERT INTO oauth_credentials (
    user_id, provider, access_token, refresh_token, id_token, api_key, account_id,
    client_id, expires_at, last_refresh, created_at, updated_at
) VALUES (
    'default_user', ?, ?, ?, ?, ?, ?, ?, ?, ?, 
    strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000
) RETURNING user_id, provider, access_token, refresh_token, id_token, api_key, account_id, 
           client_id, expires_at, last_refresh, created_at, updated_at
`

type CreateOAuthCredentialParams struct {
	Provider     string         `json:"provider"`
	AccessToken  sql.NullString `json:"access_token"`
	RefreshToken sql.NullString `json:"refresh_token"`
	IDToken      sql.NullString `json:"id_token"`
	ApiKey       sql.NullString `json:"api_key"`
	AccountID    sql.NullString `json:"account_id"`
	ClientID     string         `json:"client_id"`
	ExpiresAt    sql.NullInt64  `json:"expires_at"`
	LastRefresh  sql.NullString `json:"last_refresh"`
}

// Store a new OAuth credential for a provider
func (q *Queries) CreateOAuthCredential(ctx context.Context, arg CreateOAuthCredentialParams) (OauthCredential, error) {
	row := q.queryRow(ctx, q.createOAuthCredentialStmt, createOAuthCredential,
		arg.Provider,
		arg.AccessToken,
		arg.RefreshToken,
		arg.IDToken,
		arg.ApiKey,
		arg.AccountID,
		arg.ClientID,
		arg.ExpiresAt,
		arg.LastRefresh,
	)
	var i OauthCredential
	err := row.Scan(
		&i.UserID,
		&i.Provider,
		&i.AccessToken,
		&i.RefreshToken,
		&i.IDToken,
		&i.ApiKey,
		&i.AccountID,
		&i.ClientID,
		&i.ExpiresAt,
		&i.LastRefresh,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllOAuthCredentials = `-- name: DeleteAllOAuthCredentials :exec
DELETE FROM oauth_credentials 
WHERE user_id = 'default_user'
`

// Delete all OAuth credentials for the user
func (q *Queries) DeleteAllOAuthCredentials(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteAllOAuthCredentialsStmt, deleteAllOAuthCredentials)
	return err
}

const deleteOAuthCredential = `-- name: DeleteOAuthCredential :exec
DELETE FROM oauth_credentials 
WHERE user_id = 'default_user' AND provider = ?
`

// Delete OAuth credential for a provider
func (q *Queries) DeleteOAuthCredential(ctx context.Context, provider string) error {
	_, err := q.exec(ctx, q.deleteOAuthCredentialStmt, deleteOAuthCredential, provider)
	return err
}

const getOAuthCredential = `-- name: GetOAuthCredential :one
SELECT user_id, provider, access_token, refresh_token, id_token, api_key, account_id, 
       client_id, expires_at, last_refresh, created_at, updated_at
FROM oauth_credentials 
WHERE user_id = 'default_user' AND provider = ?
`

// Get OAuth credential for a specific provider
func (q *Queries) GetOAuthCredential(ctx context.Context, provider string) (OauthCredential, error) {
	row := q.queryRow(ctx, q.getOAuthCredentialStmt, getOAuthCredential, provider)
	var i OauthCredential
	err := row.Scan(
		&i.UserID,
		&i.Provider,
		&i.AccessToken,
		&i.RefreshToken,
		&i.IDToken,
		&i.ApiKey,
		&i.AccountID,
		&i.ClientID,
		&i.ExpiresAt,
		&i.LastRefresh,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasOAuthCredential = `-- name: HasOAuthCredential :one
SELECT COUNT(*) as count
FROM oauth_credentials 
WHERE user_id = 'default_user' AND provider = ? 
AND access_token IS NOT NULL AND access_token != ''
`

// Check if user has OAuth credential for a provider
func (q *Queries) HasOAuthCredential(ctx context.Context, provider string) (int64, error) {
	row := q.queryRow(ctx, q.hasOAuthCredentialStmt, hasOAuthCredential, provider)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listExpiredOAuthCredentials = `-- name: ListExpiredOAuthCredentials :many
SELECT user_id, provider, access_token, refresh_token, id_token, api_key, account_id,
       client_id, expires_at, last_refresh, created_at, updated_at
FROM oauth_credentials
WHERE user_id = 'default_user'
AND expires_at IS NOT NULL
AND expires_at <= (strftime('%s', 'now') + 2100)
`

// Get OAuth credentials that are expired or will expire soon (35 minute buffer)
// The 35-minute buffer ensures tokens are refreshed before they hit the 5-minute "truly expired" threshold
// With 30-minute background checks + 5-minute safety margin = zero downtime
func (q *Queries) ListExpiredOAuthCredentials(ctx context.Context) ([]OauthCredential, error) {
	rows, err := q.query(ctx, q.listExpiredOAuthCredentialsStmt, listExpiredOAuthCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthCredential{}
	for rows.Next() {
		var i OauthCredential
		if err := rows.Scan(
			&i.UserID,
			&i.Provider,
			&i.AccessToken,
			&i.RefreshToken,
			&i.IDToken,
			&i.ApiKey,
			&i.AccountID,
			&i.ClientID,
			&i.ExpiresAt,
			&i.LastRefresh,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOAuthCredentials = `-- name: ListOAuthCredentials :many
SELECT user_id, provider, access_token, refresh_token, id_token, api_key, account_id, 
       client_id, expires_at, last_refresh, created_at, updated_at
FROM oauth_credentials 
WHERE user_id = 'default_user'
ORDER BY provider
`

// List all OAuth credentials for the user
func (q *Queries) ListOAuthCredentials(ctx context.Context) ([]OauthCredential, error) {
	rows, err := q.query(ctx, q.listOAuthCredentialsStmt, listOAuthCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthCredential{}
	for rows.Next() {
		var i OauthCredential
		if err := rows.Scan(
			&i.UserID,
			&i.Provider,
			&i.AccessToken,
			&i.RefreshToken,
			&i.IDToken,
			&i.ApiKey,
			&i.AccountID,
			&i.ClientID,
			&i.ExpiresAt,
			&i.LastRefresh,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOAuthCredential = `-- name: UpdateOAuthCredential :one
UPDATE oauth_credentials 
SET access_token = ?, refresh_token = ?, id_token = ?, api_key = ?, account_id = ?,
    client_id = ?, expires_at = ?, last_refresh = ?, updated_at = strftime('%s', 'now') * 1000
WHERE user_id = 'default_user' AND provider = ?
RETURNING user_id, provider, access_token, refresh_token, id_token, api_key, account_id, 
          client_id, expires_at, last_refresh, created_at, updated_at
`

type UpdateOAuthCredentialParams struct {
	AccessToken  sql.NullString `json:"access_token"`
	RefreshToken sql.NullString `json:"refresh_token"`
	IDToken      sql.NullString `json:"id_token"`
	ApiKey       sql.NullString `json:"api_key"`
	AccountID    sql.NullString `json:"account_id"`
	ClientID     string         `json:"client_id"`
	ExpiresAt    sql.NullInt64  `json:"expires_at"`
	LastRefresh  sql.NullString `json:"last_refresh"`
	Provider     string         `json:"provider"`
}

// Update existing OAuth credential for a provider
func (q *Queries) UpdateOAuthCredential(ctx context.Context, arg UpdateOAuthCredentialParams) (OauthCredential, error) {
	row := q.queryRow(ctx, q.updateOAuthCredentialStmt, updateOAuthCredential,
		arg.AccessToken,
		arg.RefreshToken,
		arg.IDToken,
		arg.ApiKey,
		arg.AccountID,
		arg.ClientID,
		arg.ExpiresAt,
		arg.LastRefresh,
		arg.Provider,
	)
	var i OauthCredential
	err := row.Scan(
		&i.UserID,
		&i.Provider,
		&i.AccessToken,
		&i.RefreshToken,
		&i.IDToken,
		&i.ApiKey,
		&i.AccountID,
		&i.ClientID,
		&i.ExpiresAt,
		&i.LastRefresh,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOAuthCredential = `-- name: UpsertOAuthCredential :one
INSERT INTO oauth_credentials (
    user_id, provider, access_token, refresh_token, id_token, api_key, account_id,
    client_id, expires_at, last_refresh, created_at, updated_at
) VALUES (
    'default_user', ?, ?, ?, ?, ?, ?, ?, ?, ?, 
    strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000
) ON CONFLICT(user_id, provider) DO UPDATE SET
    access_token = excluded.access_token,
    refresh_token = excluded.refresh_token,
    id_token = excluded.id_token,
    api_key = excluded.api_key,
    account_id = excluded.account_id,
    client_id = excluded.client_id,
    expires_at = excluded.expires_at,
    last_refresh = excluded.last_refresh,
    updated_at = strftime('%s', 'now') * 1000
RETURNING user_id, provider, access_token, refresh_token, id_token, api_key, account_id, 
          client_id, expires_at, last_refresh, created_at, updated_at
`

type UpsertOAuthCredentialParams struct {
	Provider     string         `json:"provider"`
	AccessToken  sql.NullString `json:"access_token"`
	RefreshToken sql.NullString `json:"refresh_token"`
	IDToken      sql.NullString `json:"id_token"`
	ApiKey       sql.NullString `json:"api_key"`
	AccountID    sql.NullString `json:"account_id"`
	ClientID     string         `json:"client_id"`
	ExpiresAt    sql.NullInt64  `json:"expires_at"`
	LastRefresh  sql.NullString `json:"last_refresh"`
}

// Insert or update OAuth credential for a provider
func (q *Queries) UpsertOAuthCredential(ctx context.Context, arg UpsertOAuthCredentialParams) (OauthCredential, error) {
	row := q.queryRow(ctx, q.upsertOAuthCredentialStmt, upsertOAuthCredential,
		arg.Provider,
		arg.AccessToken,
		arg.RefreshToken,
		arg.IDToken,
		arg.ApiKey,
		arg.AccountID,
		arg.ClientID,
		arg.ExpiresAt,
		arg.LastRefresh,
	)
	var i OauthCredential
	err := row.Scan(
		&i.UserID,
		&i.Provider,
		&i.AccessToken,
		&i.RefreshToken,
		&i.IDToken,
		&i.ApiKey,
		&i.AccountID,
		&i.ClientID,
		&i.ExpiresAt,
		&i.LastRefresh,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
