// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Store a new API credential for a provider
	CreateAPICredential(ctx context.Context, arg CreateAPICredentialParams) (ApiCredential, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error)
	CreateUserPreferences(ctx context.Context, arg CreateUserPreferencesParams) (UserPreference, error)
	// Delete API credential for a provider
	DeleteAPICredential(ctx context.Context, arg DeleteAPICredentialParams) error
	// Delete all API credentials for the user
	DeleteAllAPICredentials(ctx context.Context) error
	DeleteFile(ctx context.Context, id string) error
	DeleteMessage(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	// Get API credential for a specific provider
	GetAPICredential(ctx context.Context, arg GetAPICredentialParams) (ApiCredential, error)
	GetFile(ctx context.Context, id string) (File, error)
	GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetSessionByID(ctx context.Context, id string) (GetSessionByIDRow, error)
	// Get API credential for a specific tool
	GetToolCredential(ctx context.Context, arg GetToolCredentialParams) (ApiCredential, error)
	GetUserPreferences(ctx context.Context) (UserPreference, error)
	// Check if user has API credential for a provider
	HasAPICredential(ctx context.Context, arg HasAPICredentialParams) (int64, error)
	// List all API credentials for the user
	ListAPICredentials(ctx context.Context) ([]ApiCredential, error)
	ListFilesByPath(ctx context.Context, path string) ([]File, error)
	ListFilesBySession(ctx context.Context, sessionID string) ([]File, error)
	ListLatestSessionFiles(ctx context.Context, sessionID string) ([]File, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ListMessagesForFork(ctx context.Context, arg ListMessagesForForkParams) ([]Message, error)
	ListSessionsMetadata(ctx context.Context) ([]ListSessionsMetadataRow, error)
	ListSessionsWithContent(ctx context.Context) ([]ListSessionsWithContentRow, error)
	// List all tool credentials by tool type
	ListToolCredentials(ctx context.Context, toolType string) ([]ApiCredential, error)
	ListUserMessageHistory(ctx context.Context, arg ListUserMessageHistoryParams) ([]Message, error)
	ResetUserPreferencesToDefaults(ctx context.Context) (UserPreference, error)
	// Update existing API credential for a provider
	UpdateAPICredential(ctx context.Context, arg UpdateAPICredentialParams) (ApiCredential, error)
	UpdateFile(ctx context.Context, arg UpdateFileParams) (File, error)
	UpdateMainAgentModel(ctx context.Context, arg UpdateMainAgentModelParams) (UserPreference, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (UpdateSessionRow, error)
	UpdateSubAgentModel(ctx context.Context, arg UpdateSubAgentModelParams) (UserPreference, error)
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (UserPreference, error)
	UpdateUserPreferredProvider(ctx context.Context, preferredProvider sql.NullString) (UserPreference, error)
	// Insert or update API credential for a provider
	UpsertAPICredential(ctx context.Context, arg UpsertAPICredentialParams) (ApiCredential, error)
}

var _ Querier = (*Queries)(nil)
