// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Store a new API credential for a provider
	CreateAPICredential(ctx context.Context, arg CreateAPICredentialParams) (ApiCredential, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	// Store a new OAuth credential for a provider
	CreateOAuthCredential(ctx context.Context, arg CreateOAuthCredentialParams) (OauthCredential, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error)
	CreateUserPreferences(ctx context.Context, arg CreateUserPreferencesParams) (UserPreference, error)
	// Delete API credential for a provider
	DeleteAPICredential(ctx context.Context, provider string) error
	// Delete all API credentials for the user
	DeleteAllAPICredentials(ctx context.Context) error
	// Delete all OAuth credentials for the user
	DeleteAllOAuthCredentials(ctx context.Context) error
	DeleteFile(ctx context.Context, id string) error
	DeleteMessage(ctx context.Context, id string) error
	// Delete OAuth credential for a provider
	DeleteOAuthCredential(ctx context.Context, provider string) error
	DeleteSession(ctx context.Context, id string) error
	// Get API credential for a specific provider
	GetAPICredential(ctx context.Context, provider string) (ApiCredential, error)
	GetFile(ctx context.Context, id string) (File, error)
	GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	// Get OAuth credential for a specific provider
	GetOAuthCredential(ctx context.Context, provider string) (OauthCredential, error)
	GetSessionByID(ctx context.Context, id string) (GetSessionByIDRow, error)
	GetUserPreferences(ctx context.Context) (UserPreference, error)
	// Check if user has API credential for a provider
	HasAPICredential(ctx context.Context, provider string) (int64, error)
	// Check if user has OAuth credential for a provider
	HasOAuthCredential(ctx context.Context, provider string) (int64, error)
	// List all API credentials for the user
	ListAPICredentials(ctx context.Context) ([]ApiCredential, error)
	// Get OAuth credentials that are expired or will expire soon (35 minute buffer)
	// The 35-minute buffer ensures tokens are refreshed before they hit the 5-minute "truly expired" threshold
	// With 30-minute background checks + 5-minute safety margin = zero downtime
	ListExpiredOAuthCredentials(ctx context.Context) ([]OauthCredential, error)
	ListFilesByPath(ctx context.Context, path string) ([]File, error)
	ListFilesBySession(ctx context.Context, sessionID string) ([]File, error)
	ListLatestSessionFiles(ctx context.Context, sessionID string) ([]File, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ListMessagesForFork(ctx context.Context, arg ListMessagesForForkParams) ([]Message, error)
	// List all OAuth credentials for the user
	ListOAuthCredentials(ctx context.Context) ([]OauthCredential, error)
	ListSessionsMetadata(ctx context.Context) ([]ListSessionsMetadataRow, error)
	ListSessionsWithContent(ctx context.Context) ([]ListSessionsWithContentRow, error)
	ListUserMessageHistory(ctx context.Context, arg ListUserMessageHistoryParams) ([]Message, error)
	ResetUserPreferencesToDefaults(ctx context.Context) (UserPreference, error)
	// Update existing API credential for a provider
	UpdateAPICredential(ctx context.Context, arg UpdateAPICredentialParams) (ApiCredential, error)
	UpdateFile(ctx context.Context, arg UpdateFileParams) (File, error)
	UpdateMainAgentModel(ctx context.Context, arg UpdateMainAgentModelParams) (UserPreference, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	// Update existing OAuth credential for a provider
	UpdateOAuthCredential(ctx context.Context, arg UpdateOAuthCredentialParams) (OauthCredential, error)
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (UpdateSessionRow, error)
	UpdateSubAgentModel(ctx context.Context, arg UpdateSubAgentModelParams) (UserPreference, error)
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (UserPreference, error)
	UpdateUserPreferredProvider(ctx context.Context, preferredProvider sql.NullString) (UserPreference, error)
	// Insert or update API credential for a provider
	UpsertAPICredential(ctx context.Context, arg UpsertAPICredentialParams) (ApiCredential, error)
	// Insert or update OAuth credential for a provider
	UpsertOAuthCredential(ctx context.Context, arg UpsertOAuthCredentialParams) (OauthCredential, error)
}

var _ Querier = (*Queries)(nil)
