// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_preferences.sql

package db

import (
	"context"
	"database/sql"
)

const createUserPreferences = `-- name: CreateUserPreferences :one
INSERT INTO user_preferences (
    id,
    preferred_provider,
    main_agent_model,
    main_agent_max_tokens,
    main_agent_reasoning_effort,
    sub_agent_model,
    sub_agent_max_tokens,
    sub_agent_reasoning_effort,
    created_at,
    updated_at
) VALUES (
    'default_user',
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now') * 1000,
    strftime('%s', 'now') * 1000
)
RETURNING id, preferred_provider, main_agent_model, main_agent_max_tokens, main_agent_reasoning_effort, sub_agent_model, sub_agent_max_tokens, sub_agent_reasoning_effort, created_at, updated_at
`

type CreateUserPreferencesParams struct {
	PreferredProvider        sql.NullString `json:"preferred_provider"`
	MainAgentModel           sql.NullString `json:"main_agent_model"`
	MainAgentMaxTokens       sql.NullInt64  `json:"main_agent_max_tokens"`
	MainAgentReasoningEffort sql.NullString `json:"main_agent_reasoning_effort"`
	SubAgentModel            sql.NullString `json:"sub_agent_model"`
	SubAgentMaxTokens        sql.NullInt64  `json:"sub_agent_max_tokens"`
	SubAgentReasoningEffort  sql.NullString `json:"sub_agent_reasoning_effort"`
}

func (q *Queries) CreateUserPreferences(ctx context.Context, arg CreateUserPreferencesParams) (UserPreference, error) {
	row := q.queryRow(ctx, q.createUserPreferencesStmt, createUserPreferences,
		arg.PreferredProvider,
		arg.MainAgentModel,
		arg.MainAgentMaxTokens,
		arg.MainAgentReasoningEffort,
		arg.SubAgentModel,
		arg.SubAgentMaxTokens,
		arg.SubAgentReasoningEffort,
	)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.PreferredProvider,
		&i.MainAgentModel,
		&i.MainAgentMaxTokens,
		&i.MainAgentReasoningEffort,
		&i.SubAgentModel,
		&i.SubAgentMaxTokens,
		&i.SubAgentReasoningEffort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT id, preferred_provider, main_agent_model, main_agent_max_tokens, main_agent_reasoning_effort, sub_agent_model, sub_agent_max_tokens, sub_agent_reasoning_effort, created_at, updated_at FROM user_preferences WHERE id = 'default_user' LIMIT 1
`

func (q *Queries) GetUserPreferences(ctx context.Context) (UserPreference, error) {
	row := q.queryRow(ctx, q.getUserPreferencesStmt, getUserPreferences)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.PreferredProvider,
		&i.MainAgentModel,
		&i.MainAgentMaxTokens,
		&i.MainAgentReasoningEffort,
		&i.SubAgentModel,
		&i.SubAgentMaxTokens,
		&i.SubAgentReasoningEffort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetUserPreferencesToDefaults = `-- name: ResetUserPreferencesToDefaults :one
UPDATE user_preferences 
SET 
    preferred_provider = 'anthropic',
    main_agent_model = 'claude-4-sonnet',
    main_agent_max_tokens = 4096,
    main_agent_reasoning_effort = '',
    sub_agent_model = 'claude-4-sonnet',
    sub_agent_max_tokens = 2048,
    sub_agent_reasoning_effort = ''
WHERE id = 'default_user'
RETURNING id, preferred_provider, main_agent_model, main_agent_max_tokens, main_agent_reasoning_effort, sub_agent_model, sub_agent_max_tokens, sub_agent_reasoning_effort, created_at, updated_at
`

func (q *Queries) ResetUserPreferencesToDefaults(ctx context.Context) (UserPreference, error) {
	row := q.queryRow(ctx, q.resetUserPreferencesToDefaultsStmt, resetUserPreferencesToDefaults)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.PreferredProvider,
		&i.MainAgentModel,
		&i.MainAgentMaxTokens,
		&i.MainAgentReasoningEffort,
		&i.SubAgentModel,
		&i.SubAgentMaxTokens,
		&i.SubAgentReasoningEffort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMainAgentModel = `-- name: UpdateMainAgentModel :one
UPDATE user_preferences 
SET 
    main_agent_model = ?,
    main_agent_max_tokens = ?,
    main_agent_reasoning_effort = ?
WHERE id = 'default_user'
RETURNING id, preferred_provider, main_agent_model, main_agent_max_tokens, main_agent_reasoning_effort, sub_agent_model, sub_agent_max_tokens, sub_agent_reasoning_effort, created_at, updated_at
`

type UpdateMainAgentModelParams struct {
	MainAgentModel           sql.NullString `json:"main_agent_model"`
	MainAgentMaxTokens       sql.NullInt64  `json:"main_agent_max_tokens"`
	MainAgentReasoningEffort sql.NullString `json:"main_agent_reasoning_effort"`
}

func (q *Queries) UpdateMainAgentModel(ctx context.Context, arg UpdateMainAgentModelParams) (UserPreference, error) {
	row := q.queryRow(ctx, q.updateMainAgentModelStmt, updateMainAgentModel, arg.MainAgentModel, arg.MainAgentMaxTokens, arg.MainAgentReasoningEffort)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.PreferredProvider,
		&i.MainAgentModel,
		&i.MainAgentMaxTokens,
		&i.MainAgentReasoningEffort,
		&i.SubAgentModel,
		&i.SubAgentMaxTokens,
		&i.SubAgentReasoningEffort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubAgentModel = `-- name: UpdateSubAgentModel :one
UPDATE user_preferences 
SET 
    sub_agent_model = ?,
    sub_agent_max_tokens = ?,
    sub_agent_reasoning_effort = ?
WHERE id = 'default_user'
RETURNING id, preferred_provider, main_agent_model, main_agent_max_tokens, main_agent_reasoning_effort, sub_agent_model, sub_agent_max_tokens, sub_agent_reasoning_effort, created_at, updated_at
`

type UpdateSubAgentModelParams struct {
	SubAgentModel           sql.NullString `json:"sub_agent_model"`
	SubAgentMaxTokens       sql.NullInt64  `json:"sub_agent_max_tokens"`
	SubAgentReasoningEffort sql.NullString `json:"sub_agent_reasoning_effort"`
}

func (q *Queries) UpdateSubAgentModel(ctx context.Context, arg UpdateSubAgentModelParams) (UserPreference, error) {
	row := q.queryRow(ctx, q.updateSubAgentModelStmt, updateSubAgentModel, arg.SubAgentModel, arg.SubAgentMaxTokens, arg.SubAgentReasoningEffort)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.PreferredProvider,
		&i.MainAgentModel,
		&i.MainAgentMaxTokens,
		&i.MainAgentReasoningEffort,
		&i.SubAgentModel,
		&i.SubAgentMaxTokens,
		&i.SubAgentReasoningEffort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :one
UPDATE user_preferences 
SET 
    preferred_provider = ?,
    main_agent_model = ?,
    main_agent_max_tokens = ?,
    main_agent_reasoning_effort = ?,
    sub_agent_model = ?,
    sub_agent_max_tokens = ?,
    sub_agent_reasoning_effort = ?
WHERE id = 'default_user'
RETURNING id, preferred_provider, main_agent_model, main_agent_max_tokens, main_agent_reasoning_effort, sub_agent_model, sub_agent_max_tokens, sub_agent_reasoning_effort, created_at, updated_at
`

type UpdateUserPreferencesParams struct {
	PreferredProvider        sql.NullString `json:"preferred_provider"`
	MainAgentModel           sql.NullString `json:"main_agent_model"`
	MainAgentMaxTokens       sql.NullInt64  `json:"main_agent_max_tokens"`
	MainAgentReasoningEffort sql.NullString `json:"main_agent_reasoning_effort"`
	SubAgentModel            sql.NullString `json:"sub_agent_model"`
	SubAgentMaxTokens        sql.NullInt64  `json:"sub_agent_max_tokens"`
	SubAgentReasoningEffort  sql.NullString `json:"sub_agent_reasoning_effort"`
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (UserPreference, error) {
	row := q.queryRow(ctx, q.updateUserPreferencesStmt, updateUserPreferences,
		arg.PreferredProvider,
		arg.MainAgentModel,
		arg.MainAgentMaxTokens,
		arg.MainAgentReasoningEffort,
		arg.SubAgentModel,
		arg.SubAgentMaxTokens,
		arg.SubAgentReasoningEffort,
	)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.PreferredProvider,
		&i.MainAgentModel,
		&i.MainAgentMaxTokens,
		&i.MainAgentReasoningEffort,
		&i.SubAgentModel,
		&i.SubAgentMaxTokens,
		&i.SubAgentReasoningEffort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPreferredProvider = `-- name: UpdateUserPreferredProvider :one
UPDATE user_preferences 
SET preferred_provider = ?
WHERE id = 'default_user'
RETURNING id, preferred_provider, main_agent_model, main_agent_max_tokens, main_agent_reasoning_effort, sub_agent_model, sub_agent_max_tokens, sub_agent_reasoning_effort, created_at, updated_at
`

func (q *Queries) UpdateUserPreferredProvider(ctx context.Context, preferredProvider sql.NullString) (UserPreference, error) {
	row := q.queryRow(ctx, q.updateUserPreferredProviderStmt, updateUserPreferredProvider, preferredProvider)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.PreferredProvider,
		&i.MainAgentModel,
		&i.MainAgentMaxTokens,
		&i.MainAgentReasoningEffort,
		&i.SubAgentModel,
		&i.SubAgentMaxTokens,
		&i.SubAgentReasoningEffort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
